### ISSUE TITLE
Reference node

### ISSUE THREAD

**Issue by Doggo64** [GtX-Andy/lightExtension#2]
Is there any way to get it working like in 19 without having to do guesswork with reference nodes, in my opinion, the way the script was in 19 was a lot better.

**Comment by GtX-Andy** [comment]
Hey, 
Sorry for the slow reply.

I am not sure what `guesswork` you are talking about but yes just like in the FS17 & FS19 versions you can use lights that are part of the vehicle.

These are the xml attributes if loading a light that is part of the vehicle
`
node - This is a visibility node
`
`
shaderNode - This is the node with the shader containing parameter 'lightControl'
`
`
realLightNode - This is a real light
`

```lua
<lightExtension>
    <strobeLights>
        <strobeLight node="" shaderNode="" realLightNode="" intensity="100"/>
    </strobeLights>
</lightExtension>
```

It is just a better practice to include them dynamically as this is better on system performance as they are shared objects.
To set the dynamic lights up you just import it into GE and add it to the node that will become the linkNode. You are then free to move the linkNode around containing the light easily with no guessing. When your done just delete the light from the linkNode and referance in the XML.

Hope that helps.
